global:
  scrape_interval:     5m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'minecraft'
    static_configs:
      - targets: ['stats:8000']
