version: "3.8"

services:

  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: docker.thefipster.com
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: docker.thefipster.com
      LETSENCRYPT_EMAIL: felix.reisch@live.de
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/minecraft/hosting/portainer:/data