version: "3"

networks:
  proxy:
    external: true

services:

  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      VIRTUAL_HOST: ${PORTAINER_DOMAIN}
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: ${PORTAINER_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_VOLUME}:/data
    networks: 
      - proxy
