version: '2'

networks:
  infra_default:
    external: true

services:

  prometheus:
    image: prom/prometheus:v2.24.1
    restart: always
    environment:
      VIRTUAL_HOST: prometheus.thefipster.com
      VIRTUAL_PORT: 9090
      LETSENCRYPT_HOST: prometheus.thefipster.com
    volumes:
      - /opt/minecraft/hosting/prometheus/system:/etc/prometheus
      - /opt/minecraft/hosting/prometheus/data:/prometheus
    networks:
      - infra_default

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    networks:
      - infra_default

  cadvisor:
    image: google/cadvisor:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - infra_default

  grafana:
    image: grafana/grafana:7.4.2
    restart: always
    environment:
      VIRTUAL_HOST: grafana.thefipster.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: grafana.thefipster.com
      GF_SERVER_ROOT_URL: https://grafana.thefipster.com
      GF_SECURITY_ADMIN_USER: bobama420
      GF_SECURITY_ADMIN_PASSWORD: start123X
      GF_USERS_ALLOW_SIGN_UP: "false"
    networks:
      - infra_default
