@startuml

package Admin_Stack {
    component portainer_container
}

package Infra_Stack {
    component filebrowser_container
    component proxy_container
    component letsencrypt_container
    component repo_container
    component prometheus_container
    component grafana_container
}


package Monitor_Stack {

    grafana_container -d-> prometheus_container
}

package Smp_Stack {
    component smp_filebrowser_container
    component smp_rcon_container
    component smp_prom_exporter_container
    component smp_minecraft_container
}

database NVMe
database HDD 
database SSD_2
database SSD_1

package Smp_Fs {
    interface smp_mods_volume as "Mods"
    interface smp_dynmap_volume as "Dynmap"
    interface smp_backup_volume as "Backup"

    package Minecraft_Fs {
        interface smp_logs_volume as "Logs"
        interface smp_debug_volume as "Debug"
        interface smp_world_volume as "World"
        interface smp_server_volume as "Server"
        interface smp_config_volume as "Config"
    }

    package RCON_Fs {
        interface smp_rcon_config_volume as "Config"
        interface smp_rcon_data_volume as "Data"
    }
}

package Hosting_Fs {
    interface proxy_volume as "Proxy"

    package Prometheus_Fs {
        interface prometheus_config_volume as "Config"
        interface prometheus_data_volume as "Data"
    }

    interface registry_volume as "Registry"
    interface portainer_volume as "Portainer"
}

SSD_1 -up-> proxy_volume
SSD_1 -up-> prometheus_config_volume
SSD_1 -up-> prometheus_data_volume
SSD_1 -up-> registry_volume
SSD_1 -up-> portainer_volume

NVMe -up-> smp_world_volume

SSD_2 -up-> smp_server_volume
SSD_2 -up-> smp_config_volume
SSD_2 -up-> smp_mods_volume
SSD_2 -up-> smp_logs_volume
SSD_2 -up-> smp_debug_volume
SSD_2 -up-> smp_rcon_config_volume
SSD_2 -up-> smp_rcon_data_volume

HDD -up-> smp_dynmap_volume
HDD -up-> smp_backup_volume

portainer_container -down-> portainer_volume

prometheus_container -down-> prometheus_config_volume
prometheus_container -down-> prometheus_data_volume

proxy_container -d-> proxy_volume

filebrowser_container -d-> Hosting_Fs

letsencrypt_container -r-> proxy_container

smp_filebrowser_container -down-> Smp_Fs

smp_rcon_container -d-> smp_rcon_config_volume
smp_rcon_container -d-> smp_rcon_data_volume

repo_container -d-> registry_volume

smp_prom_exporter_container -r-> smp_minecraft_container
smp_rcon_container -l-> smp_minecraft_container

smp_minecraft_container -d-> smp_world_volume
smp_minecraft_container -d-> smp_server_volume
smp_minecraft_container -d-> smp_config_volume
smp_minecraft_container -d-> smp_logs_volume
smp_minecraft_container -d-> smp_debug_volume
smp_minecraft_container -d-> smp_mods_volume
smp_minecraft_container -d-> smp_backup_volume
smp_minecraft_container -d-> smp_dynmap_volume

@enduml