version: "2"

networks:
  infra_default:
    external: true

services:

  repo:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      VIRTUAL_HOST: registry.thefipster.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: registry.thefipster.com
    volumes:
      - /opt/minecraft/hosting/registry:/var/lib/registry
    networks:
      - infra_default
